services:
  cadvisor:
    devices:
    - /dev/kmsg
    image: gcr.io/cadvisor/cadvisor
    ports:
    - 8888:8080
    privileged: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  grafana:
    image: grafana/grafana-oss
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana
  keycloak:
    command:
    - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak
    ports:
    - 8181:8080
  musketeers:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.1484375'
          memory: 1024M
    ports:
    - 8080:8080
  postgres:
    environment:
      POSTGRES_PASSWORD: admin
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - ./src/main/sql:/docker-entrypoint-initdb.d:ro
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
version: '3'
volumes:
  grafana: {}
