version: '3'

services:

  musketeers:
    #    Native build
    #image: musketeers:0.0.1-SNAPSHOT
    build: .
    deploy:
      resources:
        limits:
          #    The maximum amount of memory the container can use. If you set this option, the minimum allowed value is 6m (6 megabytes). That is, you must set the value to at least 6 megabytes.
          cpus: '0.100'
          #    Specify how much of the available CPU resources a container can use. For instance, if the host machine has two CPUs and you set --cpus="1.5", the container is guaranteed at most one and a half of the CPUs.
          memory: 128M
    ports:
      - "8080:8080"

  # C:\Windows\System32\drivers\etc\hosts
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d:ro

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./.data/prometheus:/prometheus

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./.data/grafana/var/lib/grafana:/var/lib/grafana
      - ./.data/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"

  # https://github.com/google/cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8888:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
