version: '2'

services:

  musketeers:
    build: .
    environment:
      - JAVA_OPTS=-Dspring.datasource.url=jdbc:postgresql://postgres:5432/musketeers
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d:ro

  # https://github.com/google/cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8888:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

