spring:
  application:
    name: @project.name@
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/musketeers
    username: musketeers
    password: musketeers
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true

  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

logbook:
  filter:
    enabled: true
  format:
    style: splunk
  exclude:
    - /actuator/*

logging:
  level:
    org.zalando.logbook: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true